-- 1. Display all orders with the customer who placed each order
SELECT
    o.order_id,
    c.customer_name,
    c.city,
    o.order_date
FROM Orders o
JOIN Customers c
    ON o.customer_id = c.customer_id
ORDER BY o.order_date;


-- 2. Calculate the total value of each order
SELECT
    o.order_id,
    c.customer_name,
    SUM(p.price * oi.quantity) AS order_total
FROM Orders o
JOIN Customers c
    ON o.customer_id = c.customer_id
JOIN Order_Items oi
    ON o.order_id = oi.order_id
JOIN Products p
    ON oi.product_id = p.product_id
GROUP BY o.order_id, c.customer_name
ORDER BY order_total DESC;


-- 3. Find total revenue generated by each product
SELECT
    p.product_name,
    SUM(oi.quantity) AS units_sold,
    SUM(p.price * oi.quantity) AS total_revenue
FROM Products p
JOIN Order_Items oi
    ON p.product_id = oi.product_id
GROUP BY p.product_id, p.product_name
ORDER BY total_revenue DESC;


-- 4. Find total customer spending
SELECT
    c.customer_name,
    SUM(p.price * oi.quantity) AS total_spent
FROM Customers c
JOIN Orders o
    ON c.customer_id = o.customer_id
JOIN Order_Items oi
    ON o.order_id = oi.order_id
JOIN Products p
    ON oi.product_id = p.product_id
GROUP BY c.customer_id, c.customer_name
ORDER BY total_spent DESC;


-- 5. Calculate revenue by product category
SELECT
    p.category,
    SUM(p.price * oi.quantity) AS category_revenue
FROM Products p
JOIN Order_Items oi
    ON p.product_id = oi.product_id
GROUP BY p.category
ORDER BY category_revenue DESC;


-- 6. Find customers who placed more than one order
SELECT
    c.customer_name,
    COUNT(o.order_id) AS number_of_orders
FROM Customers c
JOIN Orders o
    ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.customer_name
HAVING COUNT(o.order_id) > 1
ORDER BY number_of_orders DESC;
